module.exports = [
  { word: 'tenant', translation: '房客' },
  { word: 'landlord', translation: '房东' },
  { word: 'veterinarian', translation: '兽医' },
  { word: 'district', translation: '区域' },
  { word: 'suburb', translation: '市郊' },
  { word: 'dwelling', translation: '住处' },
  { word: 'surrounding', translation: '环境' },
  { word: 'property', translation: '财产，房地产' },
  { word: 'flat', translation: '公寓' },
  { word: 'community', translation: '社区' },
  { word: 'studio', translation: '公寓住宅' },
  { word: 'apartment', translation: '公寓住宅' },
  { word: 'neighborhood', translation: '街坊邻居' },
  { word: 'armchair', translation: '扶手椅' },
  { word: 'basement', translation: '地下室' },
  { word: 'cupboard', translation: '碗柜' },
  { word: 'cot', translation: '小屋' },
  { word: 'carpet', translation: '地毯' },
  { word: 'freezer', translation: '冰箱' },
  { word: 'drawer', translation: '抽屉' },
  { word: 'furniture', translation: '家具' },
  { word: 'kettle', translation: '水壶' },
  { word: 'laundry', translation: '洗衣房' },
  { word: 'heating', translation: '供暖' },
  { word: 'kitchen', translation: '厨房' },
  { word: 'heater', translation: '加热器' },
  { word: 'toaster', translation: '烤面包机' },
  { word: 'towel', translation: '毛巾' },
  { word: 'wardrobe', translation: '衣柜' },
  { word: 'washbasin', translation: '脸盆' },
  { word: 'cloakroom', translation: '衣帽间' },
  { word: 'bedroom', translation: '卧室' },
  { word: 'yard', translation: '院子' },
  { word: 'garden', translation: '花园' },
  { word: 'garage', translation: '车库' },
  { word: 'parking', translation: '停车场' },
  { word: 'television', translation: '电视' },
  { word: 'dining room', translation: '餐厅' },
  { word: 'rural area', translation: '农村地区' },
  { word: 'urban area', translation: '城市地区' },
  { word: 'living quarters', translation: '居住区' },
  { word: 'hall of residence', translation: '大学宿舍' },
  { word: 'microwave oven', translation: '微波炉' },
  { word: 'an alarm system', translation: '报警系统' },
  { word: 'telephone call', translation: '电话' },
  { word: 'back door', translation: '后门' },
  { word: 'silver cloth', translation: '银光呢' },
  { word: 'night table', translation: '床头柜' },
  { word: 'alarm clock', translation: '闹钟' },
  { word: 'queen size', translation: '双人' },
  { word: 'desk lamp', translation: '台灯' },
  { word: 'two-bedroomed house', translation: '双卧室别墅' },
  { word: 'single room', translation: '单间' },
  { word: 'twin room', translation: '标间' },
  { word: 'triple room', translation: '三人间' },
  { word: 'swimming pool', translation: '游泳池' },
  { word: 'living room', translation: '客厅' },
  { word: 'bill', translation: '账单' },
  { word: 'rental', translation: '租金' },
  { word: 'deposit', translation: '押金' },
  { word: 'maximum monthly rent', translation: '最高月租' },
  { word: 'document', translation: '证件' },
  { word: 'reference', translation: '介绍信' },
  { word: 'contract', translation: '合同' },
  { word: 'passport', translation: '护照' },
  { word: 'primary', translation: '初级的' },
  { word: 'intermediate', translation: '中级的' },
  { word: 'andvanced', translation: '高级的' },
  { word: 'bank statement', translation: '银行账单' },
  { word: 'extension permit', translation: '延期许可' },
  { word: 'vegetarian', translation: '素食者' },
  { word: 'diet', translation: '饮食' },
  { word: 'seefead', translation: '海鲜' },
  { word: 'bicycle', translation: '自行车' },
  { word: 'balcony', translation: '阳台' },
  { word: 'mower', translation: '割草机' },
  { word: 'parcel', translation: '包裹' },
  { word: 'kindergarten', translation: '幼儿园' },
  { word: 'childcare', translation: '儿童保健' },
  { word: 'table tennis', translation: '乒乓球' },
  { word: 'outdoor table', translation: '户外用桌子' },
  { word: 'picnic area', translation: '郊游地区' },
  { word: 'local shops', translation: '土特产商店' },
  { word: 'primary school', translation: '小学' },
  { word: 'recorded delivery', translation: '挂号信' }
]