module.exports = [
  { word: 'manage to do', translation: '设法做成某事' },
  { word: 'prey', translation: '猎物，捕猎' },
  { word: 'in the absence of', translation: '在...缺席的情况下' },
  { word: 'manoeuvre', translation: '操纵方向' },
  { word: 'obstacle', translation: '障碍物' },
  { word: 'mammal', translation: '哺乳动物' },
  { word: 'military', translation: '军事的' },
  { word: 'perceive', translation: '察觉，感知' },
  { word: 'instrument', translation: '设备' },
  { word: 'submarine', translation: '潜水艇' },
  { word: 'principal', translation: '主要的，校长' },
  { word: 'principle', translation: '原则，原理' },
  { word: 'detection', translation: '侦查，侦测' },
  { word: 'sophisticated', translation: '复杂的' },
  { word: 'term', translation: '术语，学期' },
  { word: 'call for', translation: '呼吁，召唤' },
  { word: 'revision', translation: '修订，修改' },
  { word: 'make something count', translation: '让。。。变得有价值/有意义' },
  { word: 'manipulate', translation: '控制' },
  { word: 'be entwined with', translation: '跟。。。有联系' },
  { word: 'presence', translation: '存在的' },
  { word: 'occupant', translation: '拥有者' },
  { word: 'soaring', translation: '高，增加' },
  { word: 'artifical', translation: '人工的，人造的' },
  { word: 'be inferior to', translation: '比。。。差' },
  { word: 'be superior to', translation: '比。。。好' },
  { word: 'lack access to', translation: '缺少。。。的途径' },
  { word: 'sanitation', translation: '卫生设施' },
  { word: 'consequence', translation: '推论，结论' },
  { word: 'make way for', translation: '为。。。让路' },
  { word: 'reservoir', translation: '水库' },
  { word: 'dam', translation: '大坝' },
  { word: 'extend', translation: '延长' },
  { word: 'expand', translation: '扩张' },
  { word: 'extent', translation: '程度' },
  { word: 'except', translation: '除了' },
  { word: 'expert', translation: '专家' },
  { word: 'expect', translation: '期望' },
  { word: 'shift back to', translation: '转换回到。。。' },
  { word: 'priority', translation: '优先' },
  { word: 'diminish', translation: '减少，缩小' },
  { word: 'specification', translation: '规格，说明书' },
  { word: 'criterion', translation: '规范，标准' },
  { word: 'accountability', translation: '责任制，有责任' },
  { word: 'ecological', translation: '生态的' },
  { word: 'domestic', translation: '国内，家庭内' },
  { word: 'primarily', translation: '主要的' },
  { word: 'irrigation', translation: '灌溉' },
  { word: 'consumption', translation: '消耗' },
  { word: 'maintain', translation: '维护' },
  { word: 'ownership', translation: '所有权' },
  { word: 'infrastruction', translation: '基础设施' },
  { word: 'facility', translation: '设备' },
  { word: 'minic', translation: '摹拟' },
  { word: 'imitate', translation: '模仿' },
  { word: 'stimulate', translation: '刺激' },
  { word: 'erect', translation: '使直立' },
  { word: 'dozen', translation: '一打' },
  { word: 'carpenter', translation: '木匠' },
  { word: 'sway', translation: '摇摆' },
  { word: 'Buddhism', translation: '佛教' },
  { word: 'indispensable', translation: '不可缺少的; 绝对必要的' },
  { word: 'dispense', translation: '免除，分配，分给' },
  { word: 'be dispensed with', translation: '免除' },
  { word: 'grasp', translation: '抓住; 了解' },
  { word: 'apparently', translation: '实际上' },
  { word: 'craftsman', translation: '工匠' },
  { word: 'pillar', translation: '柱子' },
  { word: 'stack', translation: '堆' },
  { word: 'corresponding', translation: '相当的，对应的' },
  { word: 'collapse', translation: '崩溃; 倒塌' },
  { word: 'absorb', translation: '吸收' },
  { word: 'digest', translation: '消化' },
  { word: 'religious', translation: '宗教的' },
  { word: 'region', translation: '区域' },
  { word: 'dynamics', translation: '动力' },
  { word: 'dynamic', translation: '动态的;' },
  { word: 'storey', translation: '楼层' },
  { word: 'fasten', translation: '系' },
  { word: 'loose', translation: '松' },
]